# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# This step lists the contents of the project for debugging purposes.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'ls -R .']
  dir: . # Run from project root


# --- Deploy shipstation-reporter Cloud Function ---
# Step 2.1: Copy requirements.txt to the root for deployment context.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'cp'
  args: ['requirements.txt', '.']
  dir: .

# Step 2.2: Move the specific function script to main.py at the root for deployment context.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'mv'
  args: ['src/shipstation_reporter.py', 'main.py']
  dir: .

# Step 2.3: Deploy the shipstation-reporter Cloud Function.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'shipstation-reporter-function'
    - '--runtime=python311'
    - '--entry-point=shipstation_reporter_http_trigger'
    - '--source=.'
    - '--trigger-http'
    - '--allow-unauthenticated'
    - '--region=us-central1'
    - '--memory=512MB'
    - '--timeout=600s'
    - '--set-env-vars=GCP_PROJECT_ID=ora-automation-project'
    - '--gen2'
  dir: .
  id: deploy-reporter
