# cloudbuild-dev.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# This step lists the contents of the project for debugging purposes.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'ls -R .']
  dir: . # Run from project root

# --- Deploy shipstation-reporter Cloud Function ---
# This step moves shipstation_reporter.py to main.py at the root.
#- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#  entrypoint: 'mv'
#  args: ['src/shipstation_reporter.py', 'main.py']
#  dir: .
#
# This step deploys the Cloud Function.
#- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#  entrypoint: 'gcloud'
#  args:
#    - 'functions'
#    - 'deploy'
#    - 'shipstation-reporter-function'
#    - '--project=ora-automation-project-dev'
#    - '--runtime=python311'
#    - '--entry-point=shipstation_reporter_http_trigger'
#    - '--source=.' # Source is the current directory (project root)
#    - '--trigger-http'
#    - '--allow-unauthenticated'
#    - '--region=us-central1'
#    - '--memory=1024MB'
#    - '--timeout=600s'
#    - '--set-env-vars=GCP_PROJECT_ID=ora-automation-project-dev'
#    - '--gen2' # Explicitly use 2nd Gen functions for Python 3.11
#    - '--set-env-vars=PYTHON_LOG_LEVEL=DEBUG'
#  dir: .
#  id: daily_shipment_processor

# --- Deploy daily-weekly-history-update Cloud Function ---
# This step moves daily_shipment_processor.py to main.py at the root.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'mv'
  args: ['src/daily_shipment_processor.py', 'main.py']
  dir: .

# This step deploys the daily-weekly-history-update Cloud Function.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'daily-weekly-history-update'
    - '--project=ora-automation-project-dev'
    - '--runtime=python311'
    - '--entry-point=daily_shipment_processor_http_trigger'
    - '--source=.'
    - '--trigger-http'
    - '--allow-unauthenticated'
    - '--region=us-central1'
    - '--memory=1024MB'
    - '--timeout=600s'
    - '--set-env-vars=GCP_PROJECT_ID=ora-automation-project-dev'
    - '--gen2'
    - '--set-env-vars=PYTHON_LOG_LEVEL=DEBUG'
  dir: .
  id: daily_weekly_history_update

# # --- Deploy shipstation-order-uploader Cloud Function ---
# # Step 1.1: Move the specific function script to main.py at the root for deployment context.
# # Note: requirements.txt is assumed to be at the project root and will be picked up by --source=.
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'mv'
#   args: ['src/shipstation_order_uploader.py', 'main.py']
#   dir: .

# # Step 1.2: Deploy the shipstation-order-uploader Cloud Function.
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'gcloud'
#   args:
#     - 'functions'
#     - 'deploy'
#     - 'shipstation-order-uploader'
#     - '--runtime=python311'
#     - '--entry-point=shipstation_order_uploader_http_trigger'
#     - '--source=.' # Source is the current directory (project root)
#     - '--trigger-http'
#     - '--allow-unauthenticated'
#     - '--region=us-central1'
#     - '--memory=1024MB'
#     - '--timeout=300s'
#     - '--set-env-vars=GCP_PROJECT_ID=ora-automation-project-dev'
#     - '--gen2' # Explicitly use 2nd Gen functions
#     # Note: For internal Python imports (e.g., from 'config' or 'src.services'),
#     # Cloud Functions typically adds the source directory (here, '.') to PYTHONPATH.
#     # If you encounter ImportError for internal modules, you might need to
#     # flatten your project structure or set PYTHONPATH explicitly in the runtime environment.
#   dir: .
#   id: deploy-order-uploader