# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# DEBUGGING STEP: List contents of the project for verification
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'ls -R .']
  dir: .

# Step to deploy shipstation-reporter-function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cp requirements.txt src/
      mv src/shipstation_reporter.py src/main.py # This is still needed for main.py

      gcloud functions deploy shipstation-reporter-function \
        --runtime python311 \
        --entry-point shipstation_reporter_http_trigger \ # CHANGED THIS LINE
        --source=./src \
        --trigger-http \
        --allow-unauthenticated \
        --region=us-central1 \
        --memory=256MB \
        --timeout=300s \
        --set-env-vars GCP_PROJECT_ID=ora-automation-project
  dir: .