# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# DEBUGGING STEP: List contents of the project for verification
- name: 'gcr.io/cloud-builders/bash:1.0' # CHANGED THIS LINE
  args: ['ls', '-R', '.'] # This command will list all files and folders recursively from the root
  dir: . # Run this command from the root of your fetched repository

# Step to deploy shipstation-reporter-function
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Copy requirements.txt to src/ for deployment context
      cp requirements.txt src/
      # Rename the script to main.py for Cloud Functions standard entry point
      mv src/shipstation_reporter.py src/main.py
      
      gcloud functions deploy shipstation-reporter-function \
        --runtime python311 \
        --entry-point main \
        --source=./src \
        --trigger-http \
        --allow-unauthenticated \
        --region=us-central1 \
        --memory=256MB \
        --timeout=300s \
        --set-env-vars GCP_PROJECT_ID=ora-automation-project
  dir: .