// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-pulse/CompactInline.tsx": () => import("../components/mockups/dashboard-pulse/CompactInline.tsx"),
  "./components/mockups/dashboard-pulse/Current.tsx": () => import("../components/mockups/dashboard-pulse/Current.tsx"),
  "./components/mockups/dashboard-pulse/GroupedActivity.tsx": () => import("../components/mockups/dashboard-pulse/GroupedActivity.tsx"),
  "./components/mockups/dashboard-pulse/PriorityBased.tsx": () => import("../components/mockups/dashboard-pulse/PriorityBased.tsx")
};
